### ISSUE TITLE
Throwing ConcurrentModificationException when trying to terminate the ConfettiManager collection 

### ISSUE THREAD

**Issue by RanjitPati** [jinatonic/confetti#13]
In AbstractActivity  the has used to terminate the ConfettiManager  collection is throwing ConcurrentModificationException . 

Bug Code:
```
 for (ConfettiManager confettiManager : activeConfettiManagers) {
                confettiManager.terminate();
    }
```

I tried to change the way for terminating the collection in below code, but still its throwing the same exception.

```
Iterator<ConfettiManager> iter = allConfettiManagers.iterator();		
while(iter.hasNext()) {					
ConfettiManager blah = iter.next();				  
if(blah != null) {					
         blah.terminate(); // Removes the 'current' item				
  }				
} 
```

**Full Stack Trace:**

> STACK_TRACE=java.util.ConcurrentModificationException
> at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:569)
> at com.openskylabs.skymo.uiscreens.ScrollerActivity.endConfitti(ScrollerActivity.java:689)
> at com.openskylabs.skymo.uiscreens.OSLCardHomeScreen.handleCardsonSwipe(OSLCardHomeScreen.java:860)
> at com.openskylabs.skymo.uiscreens.OSLCardHomeScreen.access$11(OSLCardHomeScreen.java:824)
> at com.openskylabs.skymo.uiscreens.OSLCardHomeScreen$8.onDislike(OSLCardHomeScreen.java:774)
> at com.openskylabs.skymo.cardswipe.animation.CardContainer$GestureListener.onFling(CardContainer.java:472)
> at android.view.GestureDetector.onTouchEvent(GestureDetector.java:600)
> at com.openskylabs.skymo.cardswipe.animation.CardContainer.onTouchEvent(CardContainer.java:255)
> at android.view.View.dispatchTouchEvent(View.java:7337)
> at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2257)
> at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1954)
> at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2263)
> at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1968)
> at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2263)
> at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1968)
> at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2263)
> at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1968)
> at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2263)
> at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1968)
> at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2263)
> at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1968)
> at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2263)
> at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1968)
> at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2263)
> at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1968)
> at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2263)
> at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1968)
> at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2263)
> at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1968)
> at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:1979)
> at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1429)
> at android.app.Activity.dispatchTouchEvent(Activity.java:2436)
> at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
> at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:1927)
> at android.view.View.dispatchPointerEvent(View.java:7528)
> at android.view.ViewRootImpl.deliverPointerEvent(ViewRootImpl.java:3655)
> at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:3580)
> at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:4850)
> at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:4810)
> at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:4966)
> at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:179)
> at android.os.MessageQueue.nativePollOnce(Native Method)
> at android.os.MessageQueue.next(MessageQueue.java:134)
> at android.os.Looper.loop(Looper.java:151)
> at android.app.ActivityThread.main(ActivityThread.java:5400)
> at java.lang.reflect.Method.invokeNative(Native Method)
> at java.lang.reflect.Method.invoke(Method.java:525)
> at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:841)
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:608)
> at dalvik.system.NativeStart.main(Native Method)

**Comment by jinatonic** [comment]
We don't perform any list modifications inside `terminate` so the crash is likely coming from your end.
