### ISSUE TITLE
The number of drops

### ISSUE THREAD

**Issue by 3-BodyCoding** [jinatonic/confetti#15]
Recommendation: I hope to be able to join the set to control the number of ways to drop, rather than the current second as a unit.
![qq 20170112104250](https://cloud.githubusercontent.com/assets/15881869/21875086/3b7a476a-d8b4-11e6-82c2-03b71a474d55.png)
  this.emissionRate = emissionRate / 1000f;
1000f write fixed is not good.

**Comment by jinatonic** [comment]
Unfortunately I don't understand your question. What are you trying to accomplish?

You can always extend `ConfettiManager` and override `setEmissionRate` to customize it to whatever you want.
