### ISSUE TITLE
Memory leak problems

### ISSUE THREAD

**Issue by kaizie** [jinatonic/confetti#17]
Hi, i am using the library to display some confetti like this:

CommonConfetti.explosion(container, centerX, centerY, getConfettiColor(context, score))
                        .stream(1000)
                        .setBound(new Rect(0, 0, container.getWidth(), container.getHeight()))
                        .setNumInitialCount(1)
                        .setEmissionRate(1)
                        .setEmissionDuration(1000)
                        .animate();

And i had some crashes after about a minute because of memory overflow. So i checked the Android Studio monitors and the memory was constantly raising and raising until it crashes.

Is there any tip or API to release memory that i have not seen in the wiki??
Thanks

**Comment by jinatonic** [comment]
Hm, I am unaware of this memory leak, is it reproducible in the sample project?

With your provided code, the confetti should only animate for one second (`setEmissionDuration(1000)`). Are you saying that the app crashes after the confetti stops the animation?

**Comment by kaizie** [comment]
That was the strange thing for me... the confetti does not stop playing the animation, it keeps going and going until it crashes.
I also thought that with this setup it should stop after 1 sec, but it doesn't...

But i don't really understand the difference between these two APIs:
.stream() -> Starts a stream of confetti that animates for the provided duration.
.setEmissionDuration() -> Configures how long this manager will emit new confetti after the animation starts.

What would happen if for example, i do:
.stream(1000)
.setEmissionDuration(0)
It would not emit confetti? but it would animate for 1 second (what exactly would animate???)

**Comment by jinatonic** [comment]
Ah, interesting, I wonder if it's a race condition.

This is the definition for stream
```
return confettiManager.setNumInitialCount(0)
                .setEmissionDuration(durationInMillis)
                .setEmissionRate(50)
                .animate();
```

It's literally a convenience method that does some arbitrary pre-configuration. However, note that `.animate()` call in the definition. Does your issue resolve itself if you remove the `.stream()` call? You are essentially calling `animate()` two times in a row.

**Comment by gauravarora90** [comment]
I am using it by trying the following code:

private CommonConfetti getCommonConfetti() {
        final int size = getResources().getDimensionPixelSize(R.dimen.default_confetti_size);
        final ConfettiSource confettiSource = new ConfettiSource(-size, -size);

        final Resources res = getResources();
        int goldDark = res.getColor(R.color.zotocolor);
        int goldMed = res.getColor(R.color.zotocolortrans);
        int gold = res.getColor(R.color.offer_blue);
        int goldLight = res.getColor(R.color.offer_validated_green);
        int[] colors = new int[]{goldDark, goldMed, gold, goldLight};

        final CommonConfetti commonConfetti =
                CommonConfetti.rainingConfetti(parentContainer, confettiSource, colors);

        final int velocitySlow = res.getDimensionPixelOffset(R.dimen.default_velocity_slow);
        final int velocityNormal = res.getDimensionPixelOffset(R.dimen.default_velocity_normal);
        final int velocityFast = res.getDimensionPixelOffset(R.dimen.default_velocity_fast);

        // Further configure it
        commonConfetti.getConfettiManager()
                .setVelocityX(velocityFast, velocityNormal)
                .setAccelerationX(-velocityNormal, velocitySlow)
                .setTargetVelocityX(0, velocitySlow / 2)
                .setVelocityY(velocityNormal, velocitySlow);

        return commonConfetti;
    }

And calling the confetti like this:
getCommonConfetti().infinite().animate();

And parentContainer is a FrameLayout(parent) in my xml.

But code executes without any confetti on my screen. Why so ? Am I doing something wrong ?

**Comment by kaizie** [comment]
Hi again, you can close this. It was my fault, i was creating and launching the confetti many times in a short period of time by mistake.
Thanks for you help anyway :)

**Comment by jinatonic** [comment]
Glad that you could figure it out!
