### ISSUE TITLE
Unable to show Confetti - No Crash No Confetti.

### ISSUE THREAD

**Issue by gauravarora90** [jinatonic/confetti#18]
I am using it by trying the following code:

private CommonConfetti getCommonConfetti() {
        final int size = getResources().getDimensionPixelSize(R.dimen.default_confetti_size);
        final ConfettiSource confettiSource = new ConfettiSource(-size, -size);

        final Resources res = getResources();
        int goldDark = res.getColor(R.color.zotocolor);
        int goldMed = res.getColor(R.color.zotocolortrans);
        int gold = res.getColor(R.color.offer_blue);
        int goldLight = res.getColor(R.color.offer_validated_green);
        int[] colors = new int[]{goldDark, goldMed, gold, goldLight};

        final CommonConfetti commonConfetti =
                CommonConfetti.rainingConfetti(parentContainer, confettiSource, colors);

        final int velocitySlow = res.getDimensionPixelOffset(R.dimen.default_velocity_slow);
        final int velocityNormal = res.getDimensionPixelOffset(R.dimen.default_velocity_normal);
        final int velocityFast = res.getDimensionPixelOffset(R.dimen.default_velocity_fast);

        // Further configure it
        commonConfetti.getConfettiManager()
                .setVelocityX(velocityFast, velocityNormal)
                .setAccelerationX(-velocityNormal, velocitySlow)
                .setTargetVelocityX(0, velocitySlow / 2)
                .setVelocityY(velocityNormal, velocitySlow);

        return commonConfetti;
    }

And calling the confetti like this:
getCommonConfetti().infinite().animate();

And parentContainer is a FrameLayout(parent) in my xml.

But code executes without any confetti on my screen. Why so ? Am I doing something wrong ?

**Comment by michielibiza** [comment]
@jinatonic 
I have a similar problem: I'm following the advice of the readme but no confetti is renered. I tried on Nexus 5X with android 7 using this code from the read me:
`CommonConfetti.rainingConfetti(root, new int[] {Color.BLACK }).infinite();`

after some debugging I think the problem lies in the timing: often `final long elapsedTime = valueAnimator.getCurrentPlayTime();` in the update listener in `startAnimation` is 0. Which prevents particle emission. And sometimes the time is not 0 but the `lastEmittedTimestamp` in `processNewEmission` == 0, with the same effect...

**Comment by michielibiza** [comment]
I found the problem. The sample code does not work from `Activity::onCreate` only by starting it later (like the sample project) did I manage to show the confetti

**Comment by jinatonic** [comment]
Yeah the problem with onCreate is that the view hasn't been measured yet so
the confetti manager doesn't know the bounds to show the confetti in.

**Comment by michielibiza** [comment]
Yes, I understand... Maybe it's something to put in the read me ;)

**Comment by jinatonic** [comment]
Haha good point, I'll add it so people avoid that pitfall.

**Comment by jughoor** [comment]
how do i show this anim in onCreate method ????
