### ISSUE TITLE
Add multiple Images in BitmapConfetto

### ISSUE THREAD

**Issue by GauravP123** [jinatonic/confetti#2]
Can we add multiple bitmap in  BitmapConfetto .Basically i want to add mutiple image in ShimmeringActivity without changing color 

`@Override
    public Confetto generateConfetto(Random random) {
        return new BitmapConfetto(confettoBitmaps);
    }`

**Comment by jinatonic** [comment]
Yeah easy, assuming that `confettoBitmaps` is an array of the bitmaps that you want to use, just do

```
@Override
public Confetto generateConfetto(Random random) { 
    return new BitmapConfetto(confettoBitmaps[random.nextInt(confettoBitmaps.length)]); 
}
```

This will randomly generate a bitmap from the list of bitmaps.
