### ISSUE TITLE
Add a listener for displaying confetti

### ISSUE THREAD

**Issue by Kolyall** [jinatonic/confetti#20]
Add a listener when confetti attached to view and is displayed. Also add a listener for case when confetti FadeOut from screen.

**Comment by jinatonic** [comment]
I'll release `1.1.1-SNAPSHOT` version that includes this change.

**Comment by Kolyall** [comment]
What if I need to use FallingConfettiWithListenerActivity  and FallingWithTouchActivity together ?
seems you need to create a manager and use interfaces...

**Comment by Kolyall** [comment]
Oh sorry, I see you added `.setConfettiAnimationListener(this)`
