### ISSUE TITLE
How do i stop rainingConfetti?

### ISSUE THREAD

**Issue by nandinicbit1981** [jinatonic/confetti#27]
Hello,
I am trying to stop the confetti on a button click. Which method do i use for that?

**Comment by jinatonic** [comment]
https://github.com/jinatonic/confetti/blob/master/confetti/src/main/java/com/github/jinatonic/confetti/ConfettiManager.java#L497

ConfettiManager.terminate

**Comment by nandinicbit1981** [comment]
Thanks @jinatonic 
I am trying to have confetti on the top of an alert dialog. 
What should be the container for that context?

The confetti does not show up if i have a alert dialog.
