### ISSUE TITLE
How to display confetti on the top of an alert dialog?

### ISSUE THREAD

**Issue by nandinicbit1981** [jinatonic/confetti#28]
I am trying to have confetti on the top of an alert dialog.
What should be the container for that context?

The confetti does not show up if i have a alert dialog.

**Comment by jinatonic** [comment]
The container would be the root `ViewGroup` for the `DialogFragment` or the `Dialog`. I haven't worked with `Dialog` before so I'm unsure how to get that, but for `DialogFragment` you can get the root view pretty easily.
