### ISSUE TITLE
Confetti does not work with Dialog/DialogFragment.

### ISSUE THREAD

**Issue by nandinicbit1981** [jinatonic/confetti#29]
Hi @jinatonic 
I have used the rootview for setting the container for confetti as shown : 

  CommonConfetti.rainingConfetti(
                  (ViewGroup) dialog.getWindow().getDecorView().getRootView(),new int[]{
                Color.WHITE,
                ContextCompat.getColor(context, R.color.sky_blue),
                Color.YELLOW,
                Color.GREEN,
                ContextCompat.getColor(context, R.color.red_pink),
                ContextCompat.getColor(context, R.color.teal),
                ContextCompat.getColor(context, R.color.teal_dark),
                ContextCompat.getColor(context, R.color.dark_orange)})
                .infinite();
)

I don't see confetti, nor i see an exception.

**Comment by jinatonic** [comment]
Inspect your layout hierarchy and see where `ConfettiView` is being shown. It's animating but something in the view hierarchy is probably blocking it from showing up.
