### ISSUE TITLE
Using Confetti with DialogFragment

### ISSUE THREAD

**Issue by Ionut93** [jinatonic/confetti#3]
Hei guys, can you explain me if I could use it with a DialogFragment. 
I have tried but I am unable to display the confettis. I think it is because of the container I have to pass to the ConfetiiManager, because the widht/height I receive from it is 0.
Thank you!

**Comment by jinatonic** [comment]
Ah, I haven't tested using it with a dialog fragment. If the issue is because the container view hasn't gone through measurement, then you might need to wait to create the confetti until after the view gets measured. Which `DialogFragment`'s callback are you currently using for showing the confetti?

**Comment by Ionut93** [comment]
Thank you for your reply.

So I am using the `onResume()` method to create the 

`conffetoGenerator`

, `ConfettiSource`and `confettiManager.`

**Comment by Ionut93** [comment]
Hei guys I managed to get it working. 

I had to add add the addOnGlobalLayoutListener on the view and it worked.
I post the code maybe someone will find it useful

```
view.getViewTreeObserver().addOnGlobalLayoutListener(
new ViewTreeObserver.OnGlobalLayoutListener() {

            @Override
                public void onGlobalLayout() {
                view.getViewTreeObserver().removeOnGlobalLayoutListener(this);
                confetti();     //here I create the confetti like in your sample
            }
        });

```

**Comment by jinatonic** [comment]
Ah yep that would do it, `OnGlobalLayoutListener` gets a callback once the view gets measured. Thanks for posting!
