### ISSUE TITLE
Error:This Gradle plugin requires Studio 3.0 minimum

### ISSUE THREAD

**Issue by Akshshr** [jinatonic/confetti#32]
Title says it all, forcing me to use Studio 3.0

Had to look back in the commits and roll back to Gradle Build 2.3.3 to get it to work

**Comment by jinatonic** [comment]
good point, i reverted my commit to update dependencies.

**Comment by jinatonic** [comment]
now that AS 3.0 is in stable, I'm going to re-bump this.
