### ISSUE TITLE
Adding Flip Roation instead of Clockwise or counterClockwise Rotation Animation

### ISSUE THREAD

**Issue by HarshaGadu** [jinatonic/confetti#33]
Anyway to add Flip rotation animation instead of Clockwise or Counter Clockwise rotation animation while the confetti is falling down? 

Any feedback on this feature would be greatly appreciated.

**Comment by jinatonic** [comment]
You can simply extend the Confetto class and override and draw method. The
method signature provides a rotation delta which you can then translate
into a flip degree or any custom drawing.
