### ISSUE TITLE
Is there a limitation on the size of the drawable? 

### ISSUE THREAD

**Issue by Akshshr** [jinatonic/confetti#34]
Hey! I am using a custom drawable, 2 different drawables in this case. 

One that works is 128x128 which shows up just fine.

The other one being 10x120 which doesnt show, instead it picks one drawable from the library, that looks like a rounded square. 

Any clue why I am seeing this?

**Comment by Akshshr** [comment]
![weather_rain](https://user-images.githubusercontent.com/11215286/33135784-bb7d367a-cfa3-11e7-81a4-00fd17c2b386.png)

The above doesn't show

**Comment by jinatonic** [comment]
sorry for the late reply! There isn't any limitations on the size. It sounds like you didn't properly configure the confettimanager if it's using a default one from the library. Let me know if I can help you debug.
