### ISSUE TITLE
1.1.1 release?

### ISSUE THREAD

**Issue by ImmortalNinja** [jinatonic/confetti#35]
Hi,
I really like this library and was wondering if the 1.1.1 release was going to happen soon as I could really do with the animation listener.
Thanks

**Comment by jinatonic** [comment]
Ah, I totally forgot about that. I'll do it now.

**Comment by jinatonic** [comment]
ok i released it, you should be able to see it soon-ish (up to maybe an hour or so)

**Comment by ImmortalNinja** [comment]
That’s great! Thanks
