### ISSUE TITLE
Show confetti for 5 seconds only

### ISSUE THREAD

**Issue by ronakmob** [jinatonic/confetti#38]
Hi,

How can I achieve to show confetti for 5 seconds and It should reach till the end of the screen within 5 sec timeframe. 

I am using below code but this shows confetti on screen for 13 seconds (It takes 13 seconds to clear confetti screens from the screen)

       getConfettiManager(context, container).setNumInitialCount(0)
                .setEmissionDuration(4000)
                .setEmissionRate(15)
                .animate();

Am I doing anything wrong?

I appreciate your help.

**Comment by jinatonic** [comment]
Hmm, good question, and I unfortunately don't have a great answer for it. What you can do is compute how tall the parent view is, and then dynamically compute some initial velocity / emission duration so that all of the confetti will clear out of the screen within the desired timeframe.
