### ISSUE TITLE
How to display Confetti in background?

### ISSUE THREAD

**Issue by gabriel-lins-ds** [jinatonic/confetti#39]
I wonder if it is possible to display Confetti on the background, i.e. behind any Buttons or TextViews.
I've already tried to set the elevation for the other layout components as 3dp, but the confettos are still being displayed in front of Buttons and TextViews.
I think it would be great to have an option to set confetti elevation or something like that.

Oh, and thanks for the great lib!

**Comment by zidanpiaoguo** [comment]
@GBL147852 @jinatonic Have you solved it?  Can you control the boundary?

**Comment by jinatonic** [comment]
sorry for the late reply. boundaries can be controlled manually be defining a custom parent to animate the confetti on, and then you can simply ensure that the custom parent is underneath the desired views.
