### ISSUE TITLE
Incorrect copyright

### ISSUE THREAD

**Issue by Jawnnypoo** [jinatonic/confetti#4]
Not sure if it is an issue, but it looks like the copyright of this library is attributed to Robinhood. Maybe this was a copy paste sort of error? :stuck_out_tongue:

**Comment by jinatonic** [comment]
Haha, thanks for pointing it out. It's actually intentional because I developed the library while working at Robinhood so it's technically Robinhood's IP. I simply got permission to release the library under my own github account.

**Comment by Jawnnypoo** [comment]
Ahh, gotcha. Good to know! Thanks
