### ISSUE TITLE
Cannot create ConfettiManager.ConfettiAnimationListenerAdapter object

### ISSUE THREAD

**Issue by VincentJian** [jinatonic/confetti#42]
The class ConfettiManager.ConfettiAnimationListenerAdapter should be declared static so it can be created for ConfettiManager.setConfettiAnimationListener() API that only override cared callback.

**Comment by jinatonic** [comment]
https://github.com/jinatonic/confetti/commit/967f20d1d91085bf9d4046dc371372450be16d68

**Comment by jinatonic** [comment]
good call
