### ISSUE TITLE
how to stop the one shot rain, I can't call start activity when it is animating.

### ISSUE THREAD

**Issue by jeffreyliu8** [jinatonic/confetti#43]
how to stop the one shot rain, I can't call start activity when it is animating.

**Comment by jinatonic** [comment]
I don't understand the comment "I can't call start activity when it is animating". Can you not call `terminate` to stop?

**Comment by jeffreyliu8** [comment]
Sorry, yes you are right. I can't destroy the activity by calling finish() when it is animating.

**Comment by jinatonic** [comment]
the confetti animation shouldn't affect the activity lifecycle at all. So if you are calling finish on the hosting activity, but the underlying activity ISN'T finishing, then something else is going on.
