### ISSUE TITLE
Simple Customizations

### ISSUE THREAD

**Issue by xemacobra** [jinatonic/confetti#46]
Hey,

First, thanks for the library. I recently had to do a lot of particle systems on Android and found very little options out there and yours is one of the most flexible ones I found.

I'm trying to create a bunch of simple customizations for an app I'm working on and I'm noticing that it is a bit limited to customize things without having to write my one ConfettiManager. Maybe I'm just missing something so let me know if I am.

For example, I want to be able to customize the initial position and direction of each confetto.
- While technically I can do that in the listener, I want to still follow the rules set in the `ConfettiManager` about velocity for example. There are no getters for these though. Not in `ConfettiManager` or in `Confetto` as they are `private`. Why not have getters for these values on the `Confetto`?
**Edit:** _I just realized you already did this one in your [current last commit on master](https://github.com/jinatonic/confetti/commit/e3a3b7de1684a9f66f43b56944515f9b9e0ca93e) but it is just not in the latest tagged version I added via Gradle._

- Another option was to subclass `ConfettiManager` and override `configureConfetto` but unfortunately it is also set to `private` and not `protected` so I would have to override a whole lot of functions and variables that I don't really need. Is there a specific reason that function was not set to be overridable? If not, can you please set it to `protected`.

**Comment by jinatonic** [comment]
hey sorry for dropping the ball here and not responding, with regarding your second comment, there wasn't a real reason to not make `configureConfetto` protected other than that I didn't think of the use-case to extend `ConfettiManager`. I'll make that change and do a new release.

**Comment by jinatonic** [comment]
https://github.com/jinatonic/confetti/commit/5b13cb855eae4ad4bda60f21a59e2bc675e46d73
