### ISSUE TITLE
explosion() is not working

### ISSUE THREAD

**Issue by ravisaini1990S** [jinatonic/confetti#47]
Hey 
 I am trying to use the library and have called the explosion() -

> CommonConfetti.explosion(container, centerX, centerY, new int[] {Color.RED}).oneShot();

its not showing whereas the _raining-effects_ are working fine. Could you please have a look at the issue or anything i am missing in the explosion()

**Comment by ravisaini1990S** [comment]
@jinatonic Could you please check it once

**Comment by jinatonic** [comment]
will take a look today.

**Comment by jinatonic** [comment]
The explosion sample with `oneShot` works fine.

https://github.com/jinatonic/confetti/blob/master/confetti-sample/src/main/java/com/github/jinatonic/confetti/sample/ExplosionActivity.java

You can check this by running the sample app, click on `explosion`, and click `once`.

Can you please verify that the centerX and centerY that you are passing in is valid?

**Comment by ravisaini1990S** [comment]
Thanks for quick response. I was trying it in a dialog fragment, gave valid x, y position (even tried to give hardcoded center x , y value ) but that did't work . Will check it in sample app and let you know if the issue still there.

**Comment by ravisaini1990S** [comment]
Its working fine..Thanks @jinatonic
