### ISSUE TITLE
A Tip of lower CPU usage

### ISSUE THREAD

**Issue by FIRETRAY** [jinatonic/confetti#48]
Hi there,

I read the source code and found that confettiView would be invalidated every millisecond in ValueAnimator.AnimatorUpdateListener。I used AndroidStudioProfileTool to check the cpu usage, about 6-7%。Then I changed frequency, redrawing view in every 30ms, then cpu usage would be 3-4%。And according to the Internet， Our eyes can accept this fraquence，no stumbling feeling. 

Do you think it is a good idea? Looking forward to your reply @jinatonic 

// ----------------------------
My change is: 
```
// ConfettiManager.java
private void startNewAnimation() {
        ……
        animator.addUpdateListener(new ValueAnimator.AnimatorUpdateListener() {
            private long lastUpdateTime = -1;
            @Override
            public void onAnimationUpdate(ValueAnimator valueAnimator) {
                final long elapsedTime = valueAnimator.getCurrentPlayTime();
                if(lastUpdateTime < 0) {
                    lastUpdateTime = elapsedTime;
                } else if(lastUpdateTime + 30 > elapsedTime) {
                    return;
                }
                 lastUpdateTime = elapsedTime;
               ……
            }
        });
        animator.start();
    }
```

**Comment by jinatonic** [comment]
I believe that `ValueAnimator` runs the update listener on every drawing pulse so it should be around 16ms on most devices to achieve 60fps. That makes sense with your data as manually delaying it to 30ms causes the CPU usage to halve. Unfortunately this is not something we should do in the library as we are essentially manually dropping every other frame which will affect the smoothness of the animation. Most studies show that human eyes probably can't observe past 60fps, but below 60fps there will be a noticeable difference.

Thanks for the suggestion though!
