### ISSUE TITLE
Which license do you use?

### ISSUE THREAD

**Issue by troys-code** [jinatonic/confetti#50]
This library works great and I want to include it in an app for the play store.

I would like to give you credit for the library.

Could you update the project with a license?

**Comment by jinatonic** [comment]
hey, there's license information on the bottom of the README :) it's apache common license version 2.0.

glad that you like the library!

**Comment by monika2104yadav** [comment]
Hello,

Same here. I am very happy to see this library and want to include it in my app for play store. But I really don't know what to include as a part of license information -- should I include the license as is, as mentioned at the bottom of the README?

**Comment by jinatonic** [comment]
i just added a LICENSE.txt

**Comment by monika2104yadav** [comment]
Thanks a ton.
