### ISSUE TITLE
Start Confetti from bottom and fly to the top

### ISSUE THREAD

**Issue by aditrioka** [jinatonic/confetti#51]
Can I use confetti to appear from the bottom and fly to the top? If this possible, how to configure it? do you have any sample how to do it with conffeti? Thank you :)

**Comment by jinatonic** [comment]
the confetti all animate based on their physics attributes such as velocity and acceleration. Simply making those values negative would allow you to fly from bottom to top.

**Comment by tabish075** [comment]
hi i need this effect but i am not sure how to achieve this here is my implementation so far:

`final ConfettoGenerator confettoGenerator = new ConfettoGenerator() {
                    @Override
                    public Confetto generateConfetto(Random random) {
                        final Bitmap bitmap = allPossibleConfetti.get(random.nextInt(numConfetti));
                        return new BitmapConfetto(bitmap);
                    }
                };`

                final int containerMiddleX = viewGroup.getWidth() / 2;
                final int containerMiddleY = viewGroup.getHeight() / 2;

                int size;
                int velocitySlow, velocityNormal;

                size = getResources().getDimensionPixelSize(R.dimen.big_confetti_size);
                velocitySlow = getResources().getDimensionPixelOffset(R.dimen.default_velocity_normal);
                velocityNormal = getResources().getDimensionPixelOffset(R.dimen.default_velocity_fast);

                final ConfettiSource confettiSource = new ConfettiSource(0, -size, viewGroup.getWidth(), -size);

                new ConfettiManager(LoginActivity.this, confettoGenerator, confettiSource, viewGroup)
                        .setEmissionDuration(1500)
                        .setEmissionRate(30)
                        .setVelocityX(0, velocitySlow)
                        .setVelocityY(velocityNormal, velocitySlow)
                        .setRotationalVelocity(180, 90)
                        .animate();

            }
        });
