### ISSUE TITLE
I want to start the confetti when an activity gets started. But there is no way to do so.

### ISSUE THREAD

**Issue by monika2104yadav** [jinatonic/confetti#60]
Hello,

I am trying to make an app that shows confetti when the user wins and initially it starts a new activity showing the best time and results. However, I am not able to add your confetti since it is not supposed to be in activity life cycle. What should I do?

Thanks and Regards,
Monika

**Comment by jinatonic** [comment]
you should be able to call in onCreate or onResume, the key here is that you need to use a [postDelayed](https://developer.android.com/reference/android/os/Handler#postDelayed(java.lang.Runnable,%20java.lang.Object,%20long)) because you need the parent View to be measured.

**Comment by monika2104yadav** [comment]
Thank you!
