### ISSUE TITLE
Scale [from, to] functionallity

### ISSUE THREAD

**Issue by krokyze** [jinatonic/confetti#9]
Hi,

maybe you could implement setScaleX(int from, int to), setScaleY(int from, int to) in ConfettiManager? So for example, the bitmap would scale by the time elapsed.

At the moment I'm overriding Confetti class, accessing private "millisToReachBound" field with reflection and then preScaling matrix by calculating how much time have elapsed.

**Comment by jinatonic** [comment]
Would it be enough for `Confetto.drawInternal` to include a float parameter signifying percent animated (% from start to end) so you can do any custom drawing based on the animation progress?

**Comment by krokyze** [comment]
Yes. It would even be better.

**Comment by jinatonic** [comment]
I apologize for the delay. I will put up a diff today and push a release.

**Comment by jinatonic** [comment]
I pushed out `1.1.0` release. It should be live within a few hours.

**Comment by krokyze** [comment]
Finally had time to check it out. Everything works as expected. Thanks ;)
